{
  "hash": "91dd7aef7a80562c85ef72c638d7809e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hotel Booking Cancellation & Revenue Analysis\"\ndescription: \"Identifying what drives cancellations and how booking behaviour, pricing, and stay patterns differ by country, to inform country-specific hotel marketing strategy.\"\ndate: 2026-02-03\ncategories: [Report, Code, Academic, R, tidyverse, Data Visualisation]\nimage: images/hotel-analysis-thumb.png\n---\n\n*This page is the original R source, re-executed on every site build — not a\nstatic transcription. Data loads live from the public\n[TidyTuesday hotel bookings dataset](https://github.com/rfordatascience/tidytuesday/blob/main/data/2020/2020-02-11/readme.md)\n(City Hotel & Resort Hotel bookings, Portugal, 2015-2017).*\n\n## The problem\n\nWhich factors actually drive booking cancellations, and how does customer\nbehaviour — lead time, stay length, pricing sensitivity — differ across a\nhotel's key source markets? The goal: turn that into concrete, country-level\nmarketing recommendations rather than a generic dashboard.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gt)\ndata <- read_csv(\"https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv\")\n```\n:::\n\n\n## Cancellation drivers\n\n### Cancellation rate by hotel\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhotel_names = distinct(data, hotel)\n\ncity_hotel = filter(data, hotel == \"City Hotel\")\nresort_hotel = filter(data, hotel == \"Resort Hotel\")\ncancel_rate_city = mean(city_hotel$is_canceled, na.rm = T)\ncancel_rate_res = mean(resort_hotel$is_canceled, na.rm = T)\n\ntibble(Hotel = c(\"City Hotel\", \"Resort Hotel\"),\n       `Cancellation rate` = c(cancel_rate_city, cancel_rate_res)) %>%\n  gt() %>%\n  fmt_percent(`Cancellation rate`, decimals = 1) %>%\n  tab_options(table.font.size = px(13), column_labels.font.weight = \"bold\",\n              table_body.hlines.width = px(0), table.width = pct(55))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"njreovoqmn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#njreovoqmn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#njreovoqmn thead, #njreovoqmn tbody, #njreovoqmn tfoot, #njreovoqmn tr, #njreovoqmn td, #njreovoqmn th {\n  border-style: none;\n}\n\n#njreovoqmn p {\n  margin: 0;\n  padding: 0;\n}\n\n#njreovoqmn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 55%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#njreovoqmn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#njreovoqmn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#njreovoqmn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#njreovoqmn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#njreovoqmn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#njreovoqmn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#njreovoqmn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#njreovoqmn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#njreovoqmn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#njreovoqmn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#njreovoqmn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#njreovoqmn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#njreovoqmn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 0px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#njreovoqmn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#njreovoqmn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#njreovoqmn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#njreovoqmn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#njreovoqmn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#njreovoqmn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#njreovoqmn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#njreovoqmn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#njreovoqmn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#njreovoqmn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#njreovoqmn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#njreovoqmn .gt_left {\n  text-align: left;\n}\n\n#njreovoqmn .gt_center {\n  text-align: center;\n}\n\n#njreovoqmn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#njreovoqmn .gt_font_normal {\n  font-weight: normal;\n}\n\n#njreovoqmn .gt_font_bold {\n  font-weight: bold;\n}\n\n#njreovoqmn .gt_font_italic {\n  font-style: italic;\n}\n\n#njreovoqmn .gt_super {\n  font-size: 65%;\n}\n\n#njreovoqmn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#njreovoqmn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#njreovoqmn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#njreovoqmn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#njreovoqmn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#njreovoqmn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#njreovoqmn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#njreovoqmn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#njreovoqmn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Hotel\">Hotel</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Cancellation-rate\">Cancellation rate</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Hotel\" class=\"gt_row gt_left\">City Hotel</td>\n<td headers=\"Cancellation rate\" class=\"gt_row gt_right\">41.7%</td></tr>\n    <tr><td headers=\"Hotel\" class=\"gt_row gt_left\">Resort Hotel</td>\n<td headers=\"Cancellation rate\" class=\"gt_row gt_right\">27.8%</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe City Hotel has a cancellation rate of 41.7%, compared to 27.8% for the Resort Hotel, meaning that City Hotel is 1.5 times more likely to have its booking cancelled.\nThis difference could reflect the possibility that the two hotels attract different customer segments. City Hotel bookings may be more exposed to short-notice changes, for example due to a higher share of business or short-stay travel, whereas Resort Hotel bookings may be more leisure-oriented and planned further in advance.\n\n### Lead time vs. cancellation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Correlation (lead_time, is_canceled):\", round(cor(data$lead_time, data$is_canceled), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCorrelation (lead_time, is_canceled): 0.293\n```\n\n\n:::\n\n```{.r .cell-code}\ndata %>% group_by(is_canceled) %>%\n  summarise(`Mean lead time (days)` = mean(lead_time)) %>%\n  mutate(is_canceled = if_else(is_canceled == 1, \"Cancelled\", \"Not Cancelled\")) %>%\n  rename(`Booking status` = is_canceled) %>%\n  gt() %>%\n  fmt_number(`Mean lead time (days)`, decimals = 1) %>%\n  tab_options(table.font.size = px(13), column_labels.font.weight = \"bold\",\n              table_body.hlines.width = px(0), table.width = pct(55))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"shrdwzvgaj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#shrdwzvgaj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#shrdwzvgaj thead, #shrdwzvgaj tbody, #shrdwzvgaj tfoot, #shrdwzvgaj tr, #shrdwzvgaj td, #shrdwzvgaj th {\n  border-style: none;\n}\n\n#shrdwzvgaj p {\n  margin: 0;\n  padding: 0;\n}\n\n#shrdwzvgaj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 55%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#shrdwzvgaj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#shrdwzvgaj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#shrdwzvgaj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#shrdwzvgaj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#shrdwzvgaj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#shrdwzvgaj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#shrdwzvgaj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#shrdwzvgaj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#shrdwzvgaj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#shrdwzvgaj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#shrdwzvgaj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#shrdwzvgaj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#shrdwzvgaj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 0px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#shrdwzvgaj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shrdwzvgaj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#shrdwzvgaj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#shrdwzvgaj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#shrdwzvgaj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shrdwzvgaj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#shrdwzvgaj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shrdwzvgaj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#shrdwzvgaj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shrdwzvgaj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#shrdwzvgaj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shrdwzvgaj .gt_left {\n  text-align: left;\n}\n\n#shrdwzvgaj .gt_center {\n  text-align: center;\n}\n\n#shrdwzvgaj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#shrdwzvgaj .gt_font_normal {\n  font-weight: normal;\n}\n\n#shrdwzvgaj .gt_font_bold {\n  font-weight: bold;\n}\n\n#shrdwzvgaj .gt_font_italic {\n  font-style: italic;\n}\n\n#shrdwzvgaj .gt_super {\n  font-size: 65%;\n}\n\n#shrdwzvgaj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#shrdwzvgaj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#shrdwzvgaj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#shrdwzvgaj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#shrdwzvgaj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#shrdwzvgaj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#shrdwzvgaj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#shrdwzvgaj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#shrdwzvgaj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Booking-status\">Booking status</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Mean-lead-time-(days)\">Mean lead time (days)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Booking status\" class=\"gt_row gt_left\">Not Cancelled</td>\n<td headers=\"Mean lead time (days)\" class=\"gt_row gt_right\">80.0</td></tr>\n    <tr><td headers=\"Booking status\" class=\"gt_row gt_left\">Cancelled</td>\n<td headers=\"Mean lead time (days)\" class=\"gt_row gt_right\">144.8</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = factor(is_canceled, labels = c(\"Not Cancelled\", \"Cancelled\")), y = lead_time)) +\n  geom_boxplot() +\n  labs(title = \"Lead Time Distribution by Cancellation Status\",\n       x = \"Cancelation Status\",\n       y = \"Lead Time (days)\")\n```\n\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThe correlation coefficient between lead time and cancellation status is 0.293, indicating moderate linear association between the two variables. This therefore suggests that longer lead times tend to be associated with a higher probability of cancellation.\nThis relationship is also visible in the summary statistics and the boxplot. Cancelled bookings have a substantially higher mean lead time than non-cancelled bookings, and the entire distribution of lead times for cancelled bookings is shifted toward higher values.\nOverall, the evidence suggests that longer lead times are associated with increased cancellation likelihood. This relationship makes intuitive sense, as customers who book far in advance have more time for their circumstances to change, increasing chance of cancellation.\n\n### Special requests vs. cancellation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata = data %>% mutate(has_special_req = case_when(total_of_special_requests > 0 ~ 1, TRUE ~ 0))\n\ndata %>% group_by(has_special_req) %>%\n  summarise(`Cancellation rate` = mean(is_canceled, na.rm = T)) %>%\n  mutate(has_special_req = if_else(has_special_req == 1, \"Has special request(s)\", \"No special requests\")) %>%\n  rename(`Booking type` = has_special_req) %>%\n  gt() %>%\n  fmt_percent(`Cancellation rate`, decimals = 1) %>%\n  tab_options(table.font.size = px(13), column_labels.font.weight = \"bold\",\n              table_body.hlines.width = px(0), table.width = pct(55))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"aobmepdmfi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#aobmepdmfi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#aobmepdmfi thead, #aobmepdmfi tbody, #aobmepdmfi tfoot, #aobmepdmfi tr, #aobmepdmfi td, #aobmepdmfi th {\n  border-style: none;\n}\n\n#aobmepdmfi p {\n  margin: 0;\n  padding: 0;\n}\n\n#aobmepdmfi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 55%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#aobmepdmfi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#aobmepdmfi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#aobmepdmfi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#aobmepdmfi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#aobmepdmfi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#aobmepdmfi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#aobmepdmfi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#aobmepdmfi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#aobmepdmfi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#aobmepdmfi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#aobmepdmfi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#aobmepdmfi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#aobmepdmfi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 0px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#aobmepdmfi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aobmepdmfi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#aobmepdmfi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#aobmepdmfi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#aobmepdmfi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aobmepdmfi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#aobmepdmfi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aobmepdmfi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#aobmepdmfi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aobmepdmfi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#aobmepdmfi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aobmepdmfi .gt_left {\n  text-align: left;\n}\n\n#aobmepdmfi .gt_center {\n  text-align: center;\n}\n\n#aobmepdmfi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#aobmepdmfi .gt_font_normal {\n  font-weight: normal;\n}\n\n#aobmepdmfi .gt_font_bold {\n  font-weight: bold;\n}\n\n#aobmepdmfi .gt_font_italic {\n  font-style: italic;\n}\n\n#aobmepdmfi .gt_super {\n  font-size: 65%;\n}\n\n#aobmepdmfi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#aobmepdmfi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#aobmepdmfi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#aobmepdmfi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#aobmepdmfi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#aobmepdmfi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#aobmepdmfi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#aobmepdmfi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#aobmepdmfi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Booking-type\">Booking type</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Cancellation-rate\">Cancellation rate</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Booking type\" class=\"gt_row gt_left\">No special requests</td>\n<td headers=\"Cancellation rate\" class=\"gt_row gt_right\">47.7%</td></tr>\n    <tr><td headers=\"Booking type\" class=\"gt_row gt_left\">Has special request(s)</td>\n<td headers=\"Cancellation rate\" class=\"gt_row gt_right\">21.7%</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(total_of_special_requests) %>%\n  summarise(cancel_rate = mean(is_canceled, na.rm = T)) %>%\n  ggplot(aes(x = total_of_special_requests, y = cancel_rate, fill = total_of_special_requests)) +\n  geom_col() +\n  labs(title = \"Cancelation Rate by Number of Special Requests\",\n       x = \"Number of  Special Requests\",\n       y = \"Cancelation Rate\")\n```\n\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nBookings with at least one special request have a cancellation rate of 21.7%, compared to 47.7% for bookings without any special requests. This indicates that bookings involving special requests are less likely to be cancelled.\nThe visualisation further shows a downward trend in cancellation rates as the number of special requests increases. This pattern suggests that customers who make special requests are likely to demonstrate higher commitment to their bookings, since they have invested additional effort in tailoring their stay.\n\n### Booking changes vs. cancellation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata = data %>% mutate(changed_booking = case_when(booking_changes > 0 ~ 1, TRUE ~ 0))\n\ndata %>% group_by(changed_booking) %>%\n  summarise(`Cancellation rate` = mean(is_canceled, na.rm = T)) %>%\n  mutate(changed_booking = if_else(changed_booking == 1, \"Modified booking\", \"No modifications\")) %>%\n  rename(`Booking type` = changed_booking) %>%\n  gt() %>%\n  fmt_percent(`Cancellation rate`, decimals = 1) %>%\n  tab_options(table.font.size = px(13), column_labels.font.weight = \"bold\",\n              table_body.hlines.width = px(0), table.width = pct(55))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lobmnoflqb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lobmnoflqb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lobmnoflqb thead, #lobmnoflqb tbody, #lobmnoflqb tfoot, #lobmnoflqb tr, #lobmnoflqb td, #lobmnoflqb th {\n  border-style: none;\n}\n\n#lobmnoflqb p {\n  margin: 0;\n  padding: 0;\n}\n\n#lobmnoflqb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 55%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lobmnoflqb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lobmnoflqb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lobmnoflqb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lobmnoflqb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: bold;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lobmnoflqb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lobmnoflqb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lobmnoflqb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lobmnoflqb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lobmnoflqb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lobmnoflqb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lobmnoflqb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lobmnoflqb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lobmnoflqb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 0px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lobmnoflqb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lobmnoflqb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lobmnoflqb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lobmnoflqb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lobmnoflqb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lobmnoflqb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lobmnoflqb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lobmnoflqb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lobmnoflqb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lobmnoflqb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lobmnoflqb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lobmnoflqb .gt_left {\n  text-align: left;\n}\n\n#lobmnoflqb .gt_center {\n  text-align: center;\n}\n\n#lobmnoflqb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lobmnoflqb .gt_font_normal {\n  font-weight: normal;\n}\n\n#lobmnoflqb .gt_font_bold {\n  font-weight: bold;\n}\n\n#lobmnoflqb .gt_font_italic {\n  font-style: italic;\n}\n\n#lobmnoflqb .gt_super {\n  font-size: 65%;\n}\n\n#lobmnoflqb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lobmnoflqb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lobmnoflqb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lobmnoflqb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lobmnoflqb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lobmnoflqb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lobmnoflqb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lobmnoflqb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lobmnoflqb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Booking-type\">Booking type</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Cancellation-rate\">Cancellation rate</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Booking type\" class=\"gt_row gt_left\">No modifications</td>\n<td headers=\"Cancellation rate\" class=\"gt_row gt_right\">40.9%</td></tr>\n    <tr><td headers=\"Booking type\" class=\"gt_row gt_left\">Modified booking</td>\n<td headers=\"Cancellation rate\" class=\"gt_row gt_right\">15.7%</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(booking_changes) %>%\n  summarise(cancel_rate = mean(is_canceled, na.rm = T), count = n()) %>%\n  ggplot(aes(x = booking_changes, y = cancel_rate, fill = booking_changes)) +\n  geom_col() +\n  geom_text(aes(label = count), angle = 90, vjust = 0.5, hjust = -0.2, size = 3) +\n  labs(title = \"Cancelation Rate by Booking Changes\",\n       x = \"Number of Booking Changes\",\n       y = \"Cancelation Rate\")\n```\n\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nCustomers who modify their bookings are less likely to cancel. Bookings with at least one change have a cancellation rate of only 15.7%, compared to 40.9% for bookings with no modifications.\nThe visualization reveals that cancellation rates generally decrease as the number of booking changes increases, particularly for bookings with 1-10 modifications. It should be noted that there is some variability in cancellation rates at very high numbers of booking changes, but this likely reflects the small sample sizes for these booking categories.\nOverall, the observed pattern has a clear interpretation: customers who take time to modify their bookings demonstrate active engagement and commitment to their travel plans, lowering the likelihood of cancellation.\n\n## Pricing, revenue & seasonality\n\n### Monthly average daily rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(glue)\ndata = data %>% mutate(arrival_month = ym(glue(\"{arrival_date_year} {arrival_date_month}\")))%>%\n    relocate(arrival_month)\ndata %>% group_by(arrival_month, hotel) %>%\n  summarise(monthly_adr = mean(adr, na.rm = T)) %>%\n  ggplot(aes(x = arrival_month, y = monthly_adr)) +\n  facet_wrap(~hotel, ncol = 1) +\n  geom_line() +\n  labs(title = \"Monthly Average Daily Rate\",\n       x = \"Month\",\n       y = \"Average ADR ($)\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'arrival_month'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nFor both hotels, average daily rates (ADRs) tend to peak during the summer months, particularly in August, and reach their lowest levels during the winter months, notably in November and January.\nHowever, the magnitude of seasonal variation differs substantially between the hotels. City Hotel exhibits relatively stable ADRs throughout the year, suggesting more consistent pricing and demand across seasons. In contrast, Resort Hotel shows pronounced seasonal fluctuations, with sharp increases leading into the summer period and steep declines thereafter, indicating stronger seasonality in leisure-driven demand for the Resort Hotel.\n\nAnother key observation is that the City Hotel ADR has been steadily increasing through the sample, reflected in consistent year-on-year ADR increases. This could be related to strengthening demand, improved pricing power, or changes in the hotel's positioning over time.\n\n### ADR vs. length of stay\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\ndata = data %>% mutate(nights_stayed = stays_in_week_nights + stays_in_weekend_nights)\n\np1 = data %>% group_by(nights_stayed) %>%\n  summarise(avg_adr = mean(adr, na.rm = T)) %>%\n  ggplot(aes(x = nights_stayed, y = avg_adr)) +\n  geom_col(width = 0.7) +\n   labs(title = \"Average ADR by Stay Length\",\n        x = \"Nights Stayed\",\n        y = \"Average ADR\") +\n  theme_minimal()\n\np2 = data %>% filter(nights_stayed <= 30) %>%\n  group_by(nights_stayed) %>%\n  ggplot(aes(x = factor(nights_stayed), y = adr)) +\n  geom_boxplot() +\n  scale_x_discrete(breaks = seq(0, 30, by = 5)) +\n  scale_y_continuous(limits = c(0, 200)) +\n  labs(title = \"ADR Distribution by Stay Length\",\n       x = \"Nights Stayed\",\n       y = \"ADR\") +\n  theme_minimal()\n\np1 + p2\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 4930 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThe relationship between length of stay and ADR appears to be non-linear. As stay length increases from one night to approximately seven nights, average daily rates tend to rise. Beyond this point, further increases in stay length are associated with declining ADRs.\nThis pattern is consistent with common pricing strategies where short stays capture higher per-night willingness to pay, while longer stays are incentivised through discounted average daily rates.\nOverall, the analysis suggests that longer stays are associated with lower per-night prices, particularly for stays exceeding one week.\n\n### Total monthly revenue\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% filter(is_canceled == 0, nights_stayed > 0) %>%\n  mutate(booking_revenue = adr * nights_stayed) %>%\n  group_by(arrival_month, hotel) %>%\n  summarise(total_revenue = sum(booking_revenue)) %>%\n  ggplot(aes(x = arrival_month, y = total_revenue)) +\n  geom_line() +\n  facet_wrap(~ hotel, ncol = 1) +\n  labs(title = \"Total Monthly Revenues by Hotel\",\n       x = \"Month\",\n       y = \"Total Revenue\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'arrival_month'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nTotal monthly revenues for both hotels exhibit strong seasonal patterns. Revenues peak during the summer months, with August being the highest-revenue month on average across the sample period for both hotels. Conversely, revenues are lowest around January, indicating weaker demand during the winter season.\n\nHowever, the revenue profiles differ notably between the two hotels. Resort Hotel's revenues are substantially more volatile across the year, with much sharper increases in the lead-up to summer and more pronounced declines in autumn. In contrast, City Hotel revenues are more evenly distributed across months, suggesting lower sensitivity to seasonal demand fluctuations.\n\nOne notable anomaly in the data is that in 2015, City Hotel had the highest revenue in September instead of August. This could have been caused by some temporary factors early in the sample period, but the underlying cause cannot be identified from the available data.\n\n## Booking geography\n\n### Top source markets\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>% group_by(country) %>%\n  summarise(n_bookings = n(), avg_cancel_rate = mean(is_canceled, na.rm = T)) %>%\n  arrange(desc(n_bookings)) %>%\n  slice_head(n = 5) %>%\n  ggplot(aes(x = country, y = n_bookings, fill = avg_cancel_rate)) +\n  geom_col() +\n  geom_text(aes(label = scales::percent(avg_cancel_rate, accuracy = 0.1)), vjust = -0.5, size = 3.5) +\n  labs(title = \"Countries with the Highest Number of Bookings by Cancelation Rates\",\n       x = \"Country\",\n       y = \"Number of Bookings\")\n```\n\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThe five countries with the highest number of bookings are Portugal, Great Britain, France, Spain, and Germany, with Portugal accounting for a substantially larger share of bookings than the other countries.\nHowever, there are also large differences in cancellation rates: Portugal has more than 55% of its bookings cancelled, followed by Spain at approximately 25%. This means the number of realised stays from Portugal is closer to the number of realised stays from countries such as Great Britain or France, but still dominates these countries.\n\n### Market segment composition\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = hotel, fill = market_segment)) +\n  geom_bar(position = \"fill\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(title = \"Market Segment Composition by Hotel\",\n       x = \"Hotel\",\n       y = \"Percentage\",\n       fill = \"Market Segment\")\n```\n\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThe dominant market segment for both hotels is \"Online TA\" with other notable segments for both hotels being \"Offline TA/TO\", \"Groups\", and \"Corporate\".\nThis pattern is consistent with the growing preference for online booking platforms such as Booking.com, Expedia, or Hotels.com during the sample period, which already dominated traditional offline travel agents at that time, due to their superior convenience and flexibility.\n\"Offline TA/TO\" remains a secondary but non-negligible segment for both hotels, indicating that traditional travel agents still play a role in booking activity during the sample period. Direct bookings and corporate segments represent smaller proportions of total demand, which is consistent with the limited scale of business-related and direct-channel travel relative to leisure-oriented bookings.\n\n## Country-level marketing strategy\n\nThe following analysis examines differences in booking behaviour across customer geographies with the objective of identifying insights that could inform more targeted, country-specific marketing strategies. In particular, the analysis focuses on how booking timing, length of stay, pricing, and selected guest characteristics vary across countries, and how these dimensions relate to revenue-relevant outcomes.\nTo ensure practical relevance, the analysis is restricted to countries that already represent a substantial share of bookings for each hotel. Rather than exploring expansion into new markets, the focus is on understanding behavioural differences within existing geographic segments, where targeted marketing interventions are more immediately actionable.\nThe central research question guiding this analysis is: how do booking behaviour and pricing characteristics differ across key customer geographies, and how can these differences inform the timing, positioning, and focus of hotel marketing efforts?\n\n\n::: {.cell}\n\n:::\n\n\n::: {.columns}\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"zmbmlzpeco\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zmbmlzpeco table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zmbmlzpeco thead, #zmbmlzpeco tbody, #zmbmlzpeco tfoot, #zmbmlzpeco tr, #zmbmlzpeco td, #zmbmlzpeco th {\n  border-style: none;\n}\n\n#zmbmlzpeco p {\n  margin: 0;\n  padding: 0;\n}\n\n#zmbmlzpeco .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 10px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zmbmlzpeco .gt_title {\n  color: #333333;\n  font-size: 12px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zmbmlzpeco .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zmbmlzpeco .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 10px;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zmbmlzpeco .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 10px;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zmbmlzpeco .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zmbmlzpeco .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zmbmlzpeco .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zmbmlzpeco .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zmbmlzpeco .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zmbmlzpeco .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zmbmlzpeco .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zmbmlzpeco .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zmbmlzpeco .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 0px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 0px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 0px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zmbmlzpeco .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zmbmlzpeco .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zmbmlzpeco .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zmbmlzpeco .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zmbmlzpeco .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zmbmlzpeco .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zmbmlzpeco .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zmbmlzpeco .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zmbmlzpeco .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zmbmlzpeco .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zmbmlzpeco .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zmbmlzpeco .gt_left {\n  text-align: left;\n}\n\n#zmbmlzpeco .gt_center {\n  text-align: center;\n}\n\n#zmbmlzpeco .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zmbmlzpeco .gt_font_normal {\n  font-weight: normal;\n}\n\n#zmbmlzpeco .gt_font_bold {\n  font-weight: bold;\n}\n\n#zmbmlzpeco .gt_font_italic {\n  font-style: italic;\n}\n\n#zmbmlzpeco .gt_super {\n  font-size: 65%;\n}\n\n#zmbmlzpeco .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zmbmlzpeco .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zmbmlzpeco .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zmbmlzpeco .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zmbmlzpeco .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zmbmlzpeco .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zmbmlzpeco .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#zmbmlzpeco .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#zmbmlzpeco div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>City Hotel - Top Countries</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"country\">country</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_bookings\">n_bookings</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"perc_of_total\">perc_of_total</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">PRT</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">30,960</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">39.0%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">FRA</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">8,804</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">11.1%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">DEU</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">6,084</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">7.7%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">GBR</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">5,315</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">6.7%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">ESP</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">4,611</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">5.8%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">ITA</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">3,307</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">4.2%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">BEL</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">1,894</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">2.4%</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mmexazreis\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mmexazreis table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mmexazreis thead, #mmexazreis tbody, #mmexazreis tfoot, #mmexazreis tr, #mmexazreis td, #mmexazreis th {\n  border-style: none;\n}\n\n#mmexazreis p {\n  margin: 0;\n  padding: 0;\n}\n\n#mmexazreis .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 10px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mmexazreis .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mmexazreis .gt_title {\n  color: #333333;\n  font-size: 12px;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mmexazreis .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mmexazreis .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mmexazreis .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mmexazreis .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mmexazreis .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 10px;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mmexazreis .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 10px;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mmexazreis .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mmexazreis .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mmexazreis .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mmexazreis .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mmexazreis .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mmexazreis .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mmexazreis .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mmexazreis .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mmexazreis .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 0px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 0px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 0px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mmexazreis .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mmexazreis .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mmexazreis .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mmexazreis .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mmexazreis .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mmexazreis .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mmexazreis .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mmexazreis .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mmexazreis .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mmexazreis .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mmexazreis .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mmexazreis .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mmexazreis .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mmexazreis .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mmexazreis .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mmexazreis .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mmexazreis .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mmexazreis .gt_left {\n  text-align: left;\n}\n\n#mmexazreis .gt_center {\n  text-align: center;\n}\n\n#mmexazreis .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mmexazreis .gt_font_normal {\n  font-weight: normal;\n}\n\n#mmexazreis .gt_font_bold {\n  font-weight: bold;\n}\n\n#mmexazreis .gt_font_italic {\n  font-style: italic;\n}\n\n#mmexazreis .gt_super {\n  font-size: 65%;\n}\n\n#mmexazreis .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mmexazreis .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mmexazreis .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mmexazreis .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mmexazreis .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mmexazreis .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mmexazreis .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mmexazreis .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mmexazreis div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Resort Hotel - Top Countries</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"country\">country</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n_bookings\">n_bookings</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"perc_of_total\">perc_of_total</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">PRT</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">17,630</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">44.0%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">GBR</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">6,814</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">17.0%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">ESP</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">3,957</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">9.9%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">IRL</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">2,166</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">5.4%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">FRA</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">1,611</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">4.0%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">DEU</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">1,203</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">3.0%</td></tr>\n    <tr><td headers=\"country\" class=\"gt_row gt_left\">CN</td>\n<td headers=\"n_bookings\" class=\"gt_row gt_right\">710</td>\n<td headers=\"perc_of_total\" class=\"gt_row gt_right\">1.8%</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n:::\n\nWhile the earlier country breakdown examined booking volumes, this section considers booking proportions by hotel to assess source-market composition.\nBookings for both hotels are concentrated in a small number of countries, with Portugal accounting for the largest share in each case, and the overall geographic composition being broadly similar across hotels.\nAccordingly, the analysis focuses on the five largest source markets for each hotel: Portugal, France, Germany, Great Britain, and Spain for City Hotel, and Portugal, Great Britain, Spain, Ireland, and France for Resort Hotel. This ensures that subsequent insights are derived from commercially meaningful markets.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-17-1.png){width=100%}\n:::\n:::\n\n\nLead times vary across countries for both hotels, although most bookings occur between approximately 20 and 90 days before arrival and have a long tail of bookings made further in advance. For Resort Hotel, Spanish and Portuguese customers tend to book closer to arrival, while customers from Great Britain and Ireland exhibit longer lead times. For City Hotel, cross-country differences are less pronounced, although Spain consistently shows shorter lead times than other major markets. From a marketing perspective, these patterns suggest that promotional timing may benefit from geographic differentiation. For Resort Hotel, campaigns targeting British and Irish customers may need to be launched earlier in the booking cycle, while promotions aimed at Spanish and Portuguese customers can be scheduled closer to the peak travel period. For City Hotel, more uniform campaign timing across countries appears appropriate, with limited adjustment for Spain's shorter lead times.\n\nAnother relevant dimension for marketing design is length of stay, which is examined next to assess how typical stay duration preferences vary across countries and hotels, given its implications for offer design and pricing.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-18-1.png){width=100%}\n:::\n:::\n\n\nFor City Hotel, stays are generally short across all major source markets, with the majority of bookings lasting five nights or fewer and limited variation across countries. In contrast, Resort Hotel exhibits substantially greater dispersion in stay length. Spanish and Portuguese customers tend to book shorter stays, typically under one week, while customers from Great Britain and Ireland are more likely to book stays of one week or longer. Thus, City Hotel promotions may be more effectively oriented toward short stays and weekend trips across markets, while Resort Hotel may benefit from a broader mix of stay-duration offers, with greater emphasis on longer stays when targeting British and Irish customers.\n\nThe next key consideration is price positioning, in particular identifying which markets are more suited to higher-end, premium offers and which may respond better to more affordable stay packages. A closely related dimension is the degree of stay customisation, which is also examined in the following analysis.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-19-1.png){width=100%}\n:::\n:::\n\n\nFor both hotels, geographic segments with a higher share of bookings that include special requests also tend to exhibit higher average daily rates, indicating an association between willingness to pay and demand for more customised stays. This implies that emphasising flexibility and customisation may be more effective when targeting higher-spending customer segments.\nFor City Hotel, Portuguese guests exhibit the lowest average spend per night among major source markets, suggesting they may be more responsive to value-oriented offers. For Resort Hotel, Spanish guests display the highest average prices and may represent more suitable targets for premium offerings, relative to Portugal and Great Britain, where demand appears more price-sensitive.\n\nHaving examined cross-country differences in lead time, length of stay, and average daily rate, it is useful to consider how these dimensions interact and how this may inform marketing timing and positioning across markets.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-20-1.png){width=100%}\n:::\n:::\n\n\nWhen examined jointly, longer stays tend to be associated with lower average daily rates, suggesting that price positioning reflects not only willingness to pay but also stay duration, particularly for extended stays that benefit from lower per-night pricing.\nLead time also varies systematically with price positioning. For both hotels, higher-priced stays are less commonly booked far in advance, while bookings made well ahead of arrival are more concentrated in lower to mid-range ADRs. This is especially pronounced for City Hotel, where higher-priced stays are rarely booked more than a year in advance.\nThis indicates that premium offerings may be more effectively promoted through shorter-horizon campaigns rather than early-bird promotions. Conversely, early-bird promotions may be better suited for value-oriented offers.\nFinally, effective marketing design also requires consideration of guest characteristics beyond price sensitivity and stay duration. One such dimension that captures several less directly observable preferences is whether bookings include children.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](hotel-booking-analysis_files/figure-html/unnamed-chunk-21-1.png){width=100%}\n:::\n:::\n\n\nAcross both hotels, bookings that include children tend to be made slightly further in advance than adult-only bookings, although the differences are relatively small. This suggests the timing of summer promotion campaigns does not need to differ across family and adult-only segments.\nThe heatmap indicates that Resort Hotel attracts a higher share of family bookings across key geographies, while City Hotel demand remains dominated by adult-only stays. In addition, Spanish customers exhibit a relatively high incidence of family travel for both hotels. This suggests that family-oriented offers and amenities may be particularly relevant when targeting the Spanish market, especially for Resort Hotel.\n\nTo conclude, booking behaviour differs across countries primarily through systematic differences in booking timing, stay duration, and price positioning. Higher-priced and more customised stays tend to be booked closer to arrival, while earlier bookings are more strongly associated with longer stays and lower average daily rates. Effective geographic targeting should align both the timing and positioning of marketing offers with observed country-specific booking patterns, rather than relying on uniform campaigns across markets.\n",
    "supporting": [
      "hotel-booking-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}